function catIcon(c){const m={Resto:'R',Film:'F',Café:'C',Marché:'M',Culture:'A',Balade:'B',Activité:'+',Sport:'S',Shopping:'V',Nuit:'N',Famille:'F','Bien-être':'S',Club:'D',Live:'L',Nature:'N',Escapade:'E',Jeux:'J',Créatif:'C',Gourmand:'G',Aventure:'A',Eau:'~',Animaux:'P',Curiosité:'?',Surprise:'?'};return m[c]||'•'}
function shell(x){const si=st.scope==='Moi'?'<svg viewBox="0 0 24 24"><circle cx="12" cy="8" r="3.5"/><path d="M5.5 20c1-4 3.4-5.7 6.5-5.7s5.5 1.7 6.5 5.7"/></svg>':'<svg viewBox="0 0 24 24"><circle cx="8.5" cy="8" r="3"/><circle cx="16.5" cy="9.5" r="2.5"/><path d="M3.5 20c.8-3.7 2.8-5.4 5-5.4s4.2 1.7 5 5.4M13 20c.4-2.8 1.9-4.2 3.8-4.2 1.7 0 3 1.2 3.7 4.2"/></svg>';return `<div class="app"><header class="top"><div class="brand">onfait?</div><button class="scope" onclick="scope()">${si}<span>${st.scope==='Moi'?'Pour moi':'Pour nous'}</span><span class="chev">⌄</span></button></header><main class="screen">${x}</main><nav class="tabs"><button class="tab ${ui.tab==='discover'?'on':''}" onclick="go('discover')">${ico.d}<span>Découvrir</span></button><button class="tab ${ui.tab==='saved'?'on':''}" onclick="go('saved')">${ico.s}<span>Gardé</span></button><button class="tab ${ui.tab==='profile'?'on':''}" onclick="go('profile')">${ico.p}<span>Vous</span></button></nav></div>`}
function render(){let h=!st.name?onboard():ui.tab==='discover'?discover():ui.tab==='saved'?saved():profile();app.innerHTML=h+(ui.sheet?sheet(ui.sheet):'')+(ui.ticket?ticket(ui.ticket):'');requestAnimationFrame(bindSwipe)}
function onboard(){return `<div class="onboard"><header class="onboardTop"><div class="brand">onfait?</div><span class="onboardStep">1/1</span></header><div class="onboardStage"><section class="onboardCard"><div class="onboardCopy"><h1>Comment tu t’appelles ?</h1></div><div class="onboardForm"><div class="field"><input id="name" class="input" placeholder="Prénom" autocomplete="given-name"></div><button class="primary darkPrimary" onclick="start()">Continuer</button></div></section></div></div>`}
function discover(){const r=currentRec();return shell(`<div class="discover"><div class="cardStackGhost ghost2"></div><div class="cardStackGhost ghost1"></div><section class="suggestion" id="suggestionCard"><div class="swipeStamp no">PAS MAINTENANT</div><div class="swipeStamp yes">ÇA ME TENTE</div><div class="suggestionHead"><div class="category"><span class="categoryIcon">${catIcon(r.c)}</span><span>${r.c}</span></div><span class="suggestionNo">${String(((st.rec||0)%99)+1).padStart(2,'0')}</span></div><div class="suggestionCopy"><h1>${r.t}</h1><p class="hint">${r.h}</p></div><div class="dock"><button class="primary" onclick="want()">Ça me tente</button><div class="minor"><button onclick="skip()">Pas maintenant</button><button onclick="manual()">J’ai une idée</button></div></div></section></div>`)}
function saved(){return shell(`<div class="savedHero"><div class="kick">Tes plans</div><h1 class="title">Gardé</h1></div>${st.saved.length?`<div class="savedList">${st.saved.map((x,i)=>`<button class="savedCard" onclick="detail(${i})">${x.memoryPhoto?`<img src="${x.memoryPhoto}">`:x.photoName?`<img src="/api?op=photo&name=${encodeURIComponent(x.photoName)}">`:'<div class="ph"></div>'}<div><div class="savedTitleRow"><strong>${x.place}</strong>${x.doneAt?'<span class="doneDot">fait</span>':''}</div><span class="meta">${[x.when,x.refinement,x.rating?`★ ${x.rating}`:''].filter(Boolean).join(' · ')}</span><span class="meta">${x.address||''}</span></div></button>`).join('')}</div>`:'<div class="empty">Rien ici pour l’instant.</div>'}`)}
function profile(){const initial=(st.name||'?').trim().charAt(0).toUpperCase();return shell(`<div class="profileHero"><div class="kick">Vous</div><h1 class="title">Profil</h1></div><section class="profilePanel"><div class="profileIdentity"><div class="avatar">${initial}</div><div><strong>${st.name}</strong><small>${st.scope==='Moi'?'Pour moi':'Pour nous'}</small></div></div><div class="rows"><div class="row"><span>Contexte</span><b>${st.scope}</b></div><div class="row"><span>Plans gardés</span><b>${st.saved.length}</b></div><div class="row"><span>Suggestions disponibles</span><b>${recs.length}</b></div><div class="row"><span>Onfait apprend</span><b>${Object.keys(tasteBucket().cats||{}).length} goûts</b></div></div></section><button class="quiet" onclick="resetAll()">Recommencer</button>`)}
function sheet(s){
 if(s.step==='refine'){const r=recs[s.idx],f=refine[r.c]||{question:'Qu’est-ce qui te ferait envie ?',options:['Calme','Animé','Nouveau','Pas cher','Surprends-moi']};return `<div class="sheetWrap"><div class="sheet compactSheet"><div class="grab"></div><div class="kick">${r.c}</div><h2>${f.question}</h2><div class="choices">${f.options.map(m=>`<button class="choice" onclick="pickRefinement('${escapeAttr(m)}')">${m}</button>`).join('')}</div><button class="secondary" onclick="pickRefinement('')">Peu importe</button></div></div>`}
 if(s.step==='manual')return `<div class="sheetWrap"><div class="sheet compactSheet"><div class="grab"></div><h2>Tu as envie de quoi ?</h2><input id="idea" class="input" placeholder="Ramen, bowling, expo…"><button class="primary darkPrimary" onclick="useIdea()">Continuer</button></div></div>`;
 if(s.step==='whenFirst'){const r=recs[s.idx]||recs[0],opts=whenOptions(r.c);return `<div class="sheetWrap"><div class="sheet compactSheet"><div class="grab"></div><div class="kick">${r.c}</div><h2>Quand ?</h2><div class="choices">${opts.map(w=>`<button class="choice" onclick="pickWhenBeforePlace('${escapeAttr(w)}')">${w}</button>`).join('')}</div></div></div>`}
 if(s.step==='where')return `<div class="sheetWrap"><div class="sheet compactSheet"><div class="grab"></div><h2>On part d’où ?</h2><button class="primary darkPrimary" onclick="geo()">Autour de moi</button><div class="or">ou</div><input id="city" class="input" placeholder="Ville ou quartier"><button class="secondary" onclick="searchCity()">Chercher ici</button></div></div>`;
 if(s.step==='loading')return `<div class="sheetWrap"><div class="sheet compactSheet"><div class="grab"></div><div class="loading"><div class="bars"><i></i><i></i><i></i><i></i></div>Je regarde autour de toi…</div></div></div>`;
 if(s.step==='places'){const ps=(s.places||[]).slice(0,4);return `<div class="sheetWrap"><div class="sheet resultsSheet"><div class="grab"></div><div class="kick">${ps.length||0} choix</div><h2>${recs[s.idx]?.c==='Film'?'Quel cinéma ?':'Lequel ?'}</h2>${s.error?`<div class="errorBox">${s.error}</div>`:''}<div class="places">${ps.map((p,i)=>`<button class="place" onclick="choose(${i})">${p.photoName?`<img src="/api?op=photo&name=${encodeURIComponent(p.photoName)}">`:'<div class="ph"></div>'}<div><strong>${p.displayName?.text||'Une adresse'}</strong><span class="meta">${p.rating?`★ ${p.rating}${p.userRatingCount?` · ${p.userRatingCount} avis`:''}`:''}</span><span class="meta">${p.formattedAddress||''}</span></div></button>`).join('')}</div></div></div>`}
 if(s.step==='when'){const r=recs[s.idx]||recs[0],opts=whenOptions(r.c);return `<div class="sheetWrap"><div class="sheet compactSheet"><div class="grab"></div><div class="kick">${s.place.displayName?.text||''}</div><h2>Quand ?</h2><div class="choices">${opts.map(w=>`<button class="choice" onclick="pickWhen('${escapeAttr(w)}')">${w}</button>`).join('')}</div></div></div>`}
 if(s.step==='detail'){const x=s.item,i=s.index;return `<div class="sheetWrap"><div class="sheet detailSheet"><div class="grab"></div>${x.memoryPhoto?`<img class="detailHero" src="${x.memoryPhoto}">`:x.photoName?`<img class="detailHero" src="/api?op=photo&name=${encodeURIComponent(x.photoName)}">`:''}<div class="kick">${[x.when,x.refinement].filter(Boolean).join(' · ')}</div><h2>${x.place}</h2><div class="rows"><div class="row"><span>Où</span><b>${x.address||'—'}</b></div><div class="row"><span>Avis</span><b>${x.rating?`★ ${x.rating}`:'—'}</b></div></div><div class="actionGrid"><button onclick="sharePlan(${i})">${ico.share}<span>Partager</span></button><button onclick="calendarPlan(${i})">${ico.cal}<span>Calendrier</span></button><button onclick="invitePlan(${i})">${ico.invite}<span>Inviter</span></button><button class="dangerAction" onclick="deletePlan(${i})">${ico.trash}<span>Supprimer</span></button></div>${x.googleMapsUri?`<a href="${x.googleMapsUri}" target="_blank" class="routeBtn">Itinéraire</a>`:''}<div class="memoryBlock"><div class="memoryHead"><strong>${x.doneAt?'Souvenir':'Après la sortie'}</strong><button onclick="markDone(${i})">${x.doneAt?'Fait':'Marquer fait'}</button></div>${x.memoryPhoto?`<img class="memoryPhoto" src="${x.memoryPhoto}">`:''}<input id="photo-${i}" type="file" accept="image/*" capture="environment" hidden onchange="handlePhoto(${i},this)"><div class="memoryActions"><button onclick="document.getElementById('photo-${i}').click()">${ico.photo}<span>${x.memoryPhoto?'Changer la photo':'Ajouter une photo'}</span></button><button onclick="likePlan(${i})">${ico.heart}<span>${x.likes||0}</span></button></div><div class="comments">${(x.comments||[]).map(c=>`<div class="comment">${escapeHtml(c)}</div>`).join('')}<div class="commentInput"><input id="comment-${i}" placeholder="Un commentaire…"><button onclick="addComment(${i})">Ajouter</button></div></div></div><button class="secondary" onclick="closeSheet()">Fermer</button></div></div>`}
 if(s.step==='invite'){const x=s.invite;return `<div class="sheetWrap"><div class="sheet compactSheet"><div class="grab"></div><div class="kick">Invitation</div><h2>${escapeHtml(x.place||'Un plan')}</h2><p class="sheetText">${escapeHtml(x.title||'On te propose quelque chose.')}</p><button class="primary darkPrimary" onclick="acceptInvite()">Ajouter à Gardé</button><button class="secondary" onclick="declineInvite()">Pas maintenant</button></div></div>`}
 return ''
}
function ticket(t){return `<div class="ticketScene"><div class="ticket">${t.photoName?`<img src="/api?op=photo&name=${encodeURIComponent(t.photoName)}">`:''}<div class="ticketBody"><div class="kick">Confirmé</div><h2>${t.place}</h2><p>${t.title}</p><div class="rows"><div class="row"><span>Quand</span><b>${t.when}</b></div><div class="row"><span>Avec</span><b>${st.scope}</b></div></div></div><button onclick="closeTicket()">Voir dans Gardé</button></div></div>`}
