const recs=Object.entries(catalog).flatMap(([c,items])=>items.map(([t,q,h],i)=>({id:`${c}-${i}`,c,t,q,h})));
function tasteBucket(scope=st.scope){st.taste=st.taste&&typeof st.taste==='object'?st.taste:{};if(!st.taste[scope])st.taste[scope]={cats:{},refs:{},actions:{},seen:[],recent:[],events:0};const b=st.taste[scope];b.cats=b.cats||{};b.refs=b.refs||{};b.actions=b.actions||{};b.seen=Array.isArray(b.seen)?b.seen:[];b.recent=Array.isArray(b.recent)?b.recent:[];return b}
function signal(cat,ref,delta,action='generic'){const b=tasteBucket();b.events=(b.events||0)+1;b.cats[cat]=(b.cats[cat]||0)+delta;if(ref)b.refs[ref]=(b.refs[ref]||0)+delta*.7;b.actions[action]=(b.actions[action]||0)+1;save()}
function timeBoost(cat){const d=new Date(),h=d.getHours(),day=d.getDay(),weekend=day===0||day===6;let n=0;if(h<11&&['Café','Marché','Balade','Nature','Gourmand','Famille'].includes(cat))n+=.95;if(h>=11&&h<15&&['Resto','Café','Marché','Shopping','Culture','Gourmand'].includes(cat))n+=.55;if(h>=15&&h<19&&['Culture','Shopping','Bien-être','Nature','Créatif','Escapade','Eau','Balade','Activité'].includes(cat))n+=.65;if(h>=18&&h<23&&['Resto','Film','Activité','Live','Jeux','Nuit','Club','Bien-être'].includes(cat))n+=.9;if(h>=23&&['Nuit','Club','Resto','Balade'].includes(cat))n+=1.2;if(weekend&&['Marché','Escapade','Nature','Famille','Live','Aventure','Eau'].includes(cat))n+=.5;return n}
function scopeBoost(cat){if(st.scope==='Nous')return ['Resto','Film','Activité','Jeux','Live','Nuit','Club','Bien-être','Escapade','Créatif'].includes(cat)?.45:0;return ['Café','Balade','Culture','Bien-être','Nature','Shopping','Curiosité','Sport'].includes(cat)?.3:0}
function savedAffinity(cat){const xs=(st.saved||[]).filter(x=>x&&x.category===cat);if(!xs.length)return 0;const done=xs.filter(x=>x.done).length,liked=xs.reduce((a,x)=>a+(x.likes||0),0),shared=xs.filter(x=>x.invited||x.sharedFrom).length;return Math.min(1.5,xs.length*.16+done*.22+liked*.12+shared*.16)}
function diversityBoost(cat){const b=tasteBucket(),recent=b.recent||[];if(recent[0]===cat)return-1.4;if(recent.includes(cat))return-.72;return .18}
function explorationRate(){const b=tasteBucket(),e=b.events||0;if(e<6)return .48;if(e<20)return .4;if(e<60)return .34;return .29}
function categoryScore(cat){const b=tasteBucket();return (b.cats[cat]||0)*.34+savedAffinity(cat)+timeBoost(cat)+scopeBoost(cat)+diversityBoost(cat)}
function pickNextRec(){const b=tasteBucket(),seen=new Set(b.seen||[]);let pool=recs.filter(r=>!seen.has(r.id));if(pool.length<Math.max(28,recs.length*.16)){b.seen=[];pool=[...recs]}const explore=Math.random()<explorationRate();if(explore){const grouped=[...new Set(pool.map(r=>r.c))].map(c=>({c,score:categoryScore(c)+(b.cats[c]||0<0?-.15:0)})).sort((a,z)=>a.score-z.score);const band=grouped.slice(0,Math.max(7,Math.ceil(grouped.length*.5)));const pick=band[Math.floor(Math.random()*band.length)]?.c||grouped[0]?.c;const options=pool.filter(r=>r.c===pick);return options[Math.floor(Math.random()*options.length)]||pool[Math.floor(Math.random()*pool.length)]||recs[0]}const scored=pool.map(r=>({r,score:1+categoryScore(r.c)+Math.random()*.75})).sort((a,z)=>z.score-a.score);const top=scored.slice(0,Math.min(10,scored.length));const cap=Math.min(4,top.length);return top[Math.floor(Math.random()*Math.max(1,cap))]?.r||recs[0]}
function currentRec(){const b=tasteBucket();let r=recs.find(x=>x.id===b.current);if(!r){r=pickNextRec();b.current=r.id;save()}return r}
function advanceRec(){const b=tasteBucket(),r=currentRec();b.seen.push(r.id);if(b.seen.length>320)b.seen=b.seen.slice(-220);b.recent=[r.c,...b.recent.filter(x=>x!==r.c)].slice(0,4);b.current=null;st.rec=(st.rec||0)+1;save()}
function topTasteTerms(limit=2){const b=tasteBucket();return Object.entries(b.refs||{}).filter(([k,v])=>k&&v>.22&&!/surprends|peu importe|carte blanche/i.test(k)).sort((a,z)=>z[1]-a[1]).slice(0,limit).map(([k])=>k)}
function inferCategory(q){q=String(q||'').toLowerCase();const tests=[['Bien-être',/(spa|massage|hammam|sauna|head spa|bien.?être|soin)/],['Club',/(bo[iî]te|club|danser|dance|techno|house|afro|hip.?hop|reggaeton)/],['Film',/(cin[eé]|film|imax|dolby)/],['Marché',/(march[eé]|brocante|vide.?grenier|vintage)/],['Culture',/(expo|mus[eé]e|galerie|art|monument)/],['Resto',/(resto|restaurant|d[iî]ner|manger|brunch)/],['Café',/(caf[eé]|go[uû]ter|salon de th[eé])/],['Nature',/(for[eê]t|lac|rando|nature|parc)/],['Live',/(concert|stand.?up|th[eé][aâ]tre|jazz|spectacle)/],['Jeux',/(bowling|arcade|laser|billard|quiz|vr|escape)/],['Sport',/(padel|badminton|escalade|sport|piscine|karting)/],['Créatif',/(poterie|peinture|atelier|c[eé]ramique|parfum)/],['Gourmand',/(p[aâ]tisserie|street food|food court|d[eé]gustation)/],['Animaux',/(zoo|aquarium|cheval|animaux|ferme)/],['Aventure',/(accrobranche|aventure|sensation|chute libre|kayak)/],['Eau',/(bateau|paddle|plage|aquatique|p[eé]dalo)/],['Escapade',/(ch[aâ]teau|village|escapade|day trip|journ[eé]e)/],['Shopping',/(shopping|friperie|boutique|librairie|sneaker)/]];return (tests.find(([,rx])=>rx.test(q))||['Surprise'])[0]}
function searchHintsFor(cat,state){const learned=topTasteTerms(2),out=[];const ref=state.refinement||'';if(ref&&!/surprends|carte blanche|peu importe/i.test(ref))out.push(ref);const canLearn=!['Film','Marché','Club'].includes(cat);if(canLearn&&learned.length&&Math.random()<.55)out.push(learned[0]);return [...new Set(out)].slice(0,2)}
function buildSearchQuery(r,state){const cat=state.manualCategory||r.c,baseQ=state.manualQuery||r.q,hints=searchHintsFor(cat,state);if(state.manualQuery)return [state.manualQuery,...hints].filter(Boolean).join(' ');const special={Film:'cinéma',Marché:'marché brocante',Club:'club discothèque',Nuit:'bar soirée',Live:'concert spectacle',"Bien-être":'spa massage bien-être',Nature:'parc nature',Escapade:'attraction touristique',Eau:'base de loisirs activité nautique'};return [special[cat]||baseQ,...hints].filter(Boolean).join(' ')}
